import 'package:flutter/material.dart';

const kPrimaryColor = Color(0xFF6F35A5);
const kPrimaryBackgroundColor = Color(0xFFfbf5f1);
const kSecondaryColor = Color(0xFF70a288);
const kPrimaryLightColor = Color(0xFFF1E6FF);
const List<String> lettersNumbersimagesUrls = [
  "assets/images/numbers/Arabic_numbers_0.png",
  "assets/images/numbers/Arabic_numbers_1.png",
  "assets/images/numbers/Arabic_numbers_2.png",
  "assets/images/numbers/Arabic_numbers_3.png",
  "assets/images/numbers/Arabic_numbers__4.png",
  "assets/images/numbers/Arabic_numbers__5.png",
  "assets/images/numbers/Arabic_numbers__6.png",
  "assets/images/numbers/Arabic_numbers__7.png",
  "assets/images/numbers/Arabic_numbers_8.png",
  "assets/images/numbers/Arabic_numbers_9.png",
  "assets/images/alphabet/arabic alphabets continued_أ ملون.png",
  "assets/images/alphabet/arabic alphabets continued_برتقال ملون.png",
  "assets/images/alphabet/arabic alphabets continued_تفاح ملون.png",
  "assets/images/alphabet/arabic alphabets continued_ثلج ملون.png",
  "assets/images/alphabet/arabic alphabets continued_جزر ملون .png",
  "assets/images/alphabet/arabic alphabets continued_حذاء ملون.png",
  "assets/images/alphabet/arabic_alphabets_continued_خس_ملون.png",
  "assets/images/alphabet/arabic alphabets continued_دب ملون.png",
  "assets/images/alphabet/arabic alphabets continued_ذرة ملون.png",
  "assets/images/alphabet/arabic alphabets continued_رمان ملون.png",
  "assets/images/alphabet/arabic alphabets continued_زهرة ملون.png",
  "assets/images/alphabet/arabic alphabets continued_سمكة ملونة.png",
  "assets/images/alphabet/arabic alphabets continued_شمس ملون.png",
  "assets/images/alphabet/arabic alphabets continued_صندوص ملون.png",
  "assets/images/alphabet/arabic alphabets continued_ضرس ملون.png",
  "assets/images/alphabet/arabic alphabets continued_طماطم ملون.png",
  "assets/images/alphabet/arabic alphabets continued_ظرف ملون.png",
  "assets/images/alphabet/arabic alphabets continued_عصفور ملون.png",
  "assets/images/alphabet/arabic alphabets continued_غيمة ملون.png",
  "assets/images/alphabet/arabic alphabets continued_فراولة ملون.png",
  "assets/images/alphabet/arabic alphabets continued_قلم ملون.png",
  "assets/images/alphabet/arabic alphabets continued_كتاب ملون.png",
  "assets/images/alphabet/arabic alphabets continued_ليمون ملون.png",
  "assets/images/alphabet/arabic alphabets continued_منظاد ملون.png",
  "assets/images/alphabet/arabic alphabets continued_نحلة ملون.png",
  "assets/images/alphabet/arabic alphabets continued_هرة ملون .png",
  "assets/images/alphabet/arabic alphabets continued_ورقة ملون.png",
  "assets/images/alphabet/arabic alphabets continued_يد ملون.png",
];

const nameOfNumbers = [
  'صفر',
  'واحد',
  'اثنين',
  'ثلاثة',
  'أربعة',
  'خمسة',
  'ستة',
  'سبعة',
  'ثمانية',
  'تسعة'
];

const nameOfLetters = [
  'الف',
  'باء',
  'تاء',
  'ثاء',
  'جيم',
  'حاء',
  'خاء',
  'دال',
  'ذال',
  'راء',
  'زاء',
  'سين',
  'شين',
  'صاد',
  'ضاد',
  'طاء',
  'ظاء',
  'عين',
  'غين',
  'فاء',
  'قاف',
  'كاف',
  'لام',
  'ميم',
  'نون',
  'هاء',
  'واو',
  'ياء',
];
